#!/bin/sh

echo 'Building the demo'

git stash -q --keep-index

yarn build:demo 
status=$?
if [ $status -ne 0 ]; then
    echo "Build error"
    exit $status
fi

git add docs

git stash pop -q

exit $status